# Generated by Django 2.1.7 on 2019-02-19 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDB', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
