# Generated by Django 2.1.7 on 2019-02-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MovieDB', '0004_auto_20190219_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_year', models.IntegerField()),
                ('movie_rated', models.TextField()),
                ('movie_released', models.TextField()),
                ('movie_runtime', models.IntegerField()),
                ('movie_genre', models.TextField()),
                ('movie_director', models.TextField()),
                ('movie_writer', models.TextField()),
                ('movie_actors', models.TextField()),
                ('movie_plot', models.TextField()),
                ('movie_poster', models.TextField()),
                ('movie_imdbrating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('movie_imdbvotes', models.IntegerField()),
                ('movie_imdbid', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_header', models.CharField(max_length=200)),
                ('test_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('movie_title', 'movie_year')},
        ),
    ]
