# Generated by Django 2.1.7 on 2019-02-19 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDB', '0005_auto_20190219_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_actors',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_director',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_genre',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_imdbid',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_imdbrating',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_imdbvotes',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_plot',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_poster',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_rated',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_released',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_runtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='movie_writer',
            field=models.TextField(null=True),
        ),
    ]
