# Generated by Django 2.1.7 on 2019-02-20 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDB', '0006_auto_20190219_2343'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='movie_added',
            field=models.TextField(null=True),
        ),
    ]
