# Generated by Django 2.1.7 on 2019-03-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDB', '0007_movie_movie_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='manual',
            field=models.TextField(null=True),
        ),
    ]
