# Generated by Django 2.1.7 on 2019-03-31 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieDB', '0008_movie_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='filepath',
            field=models.TextField(null=True),
        ),
    ]
